import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { twMerge } from 'tailwind-merge'

/** typefaces */
const generalSans = localFont({
  src: [
    {
      path: './../../public/fonts/GeneralSans-Variable.ttf',
      style: 'normal',
    },
    {
      path: './../../public/fonts/GeneralSans-VariableItalic.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-general-sans',
})
const bespokeSerif = localFont({
  src: [
    {
      path: './../../public/fonts/BespokeSerif-Variable.ttf',
      style: 'normal',
    },
    {
      path: './../../public/fonts/BespokeSerif-VariableItalic.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-bespoke-serif',
})

/** layout */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const styles = twMerge(
    'bg-black text-white',
    generalSans.variable,
    bespokeSerif.variable,
  )

  return (
    <html lang="en">
      <body className={styles}>{children}</body>
    </html>
  )
}
